#!/bin/bash

action=$(zenity --list --title="Éteindre le PC" --column="Action" "Éteindre" "Redémarrer" "Annuler")

case $action in
    "Éteindre")
        systemctl poweroff
        ;;
    "Redémarrer")
        systemctl reboot
        ;;
    *)
        ;;
esac

